version: '3'
services:
  client-test:
    container_name: client-test
    build:
      context: ./client
    ports:
      # - "7167:7167"
      # - "5011:5011"
      - "5011:80"
      - "7167:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    volumes:
      - ../ClientApp:/app
    command: ["dotnet", "watch", "run"]
